[buildPlans.iosevka-li9htmare]
family = "Iosevka Li9htmare"
serifs = "sans"
spacing = "normal"
export-glyph-names = false

[buildPlans.iosevka-li9htmare.variants]
inherits = "ss09"
[buildPlans.iosevka-li9htmare.variants.design]
capital-i = "short-serifed"
zero = "slashed-split"
one = "no-base"

[buildPlans.iosevka-li9htmare.ligations]
inherits = "default-calt"
disables = ["llgg"]

[buildPlans.iosevka-li9htmare.weights.regular]
shape = 400
menu = 400
css = 400
[buildPlans.iosevka-li9htmare.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-li9htmare.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
[buildPlans.iosevka-li9htmare.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.iosevka-li9htmare.widths.normal]
shape = 500
menu = 5
css = "normal"


[buildPlans.iosevka-term-li9htmare]
family = "Iosevka Term Li9htmare"
serifs = "sans"
spacing = "term"
# Setting this to `true` will increase file footprint, however this is necessary for ligature support in Kitty.
export-glyph-names = true

[buildPlans.iosevka-term-li9htmare.variants]
inherits = "ss09"
[buildPlans.iosevka-term-li9htmare.variants.design]
capital-i = "short-serifed"
zero = "slashed-split"
one = "no-base"

[buildPlans.iosevka-term-li9htmare.ligations]
inherits = "default-calt"
disables = ["llgg"]

[buildPlans.iosevka-term-li9htmare.weights.regular]
shape = 400
menu = 400
css = 400
[buildPlans.iosevka-term-li9htmare.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-term-li9htmare.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
[buildPlans.iosevka-term-li9htmare.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.iosevka-term-li9htmare.widths.normal]
shape = 500
menu = 5
css = "normal"


[collectPlans.iosevka-li9htmare]
from = [
  "iosevka-li9htmare",
  "iosevka-term-li9htmare",
]
